---
title: "EVAX"
author: "Iyed Ghedamsi"
date: "7/20/2021"
output:
  html_document: 
    toc: yes
    fig_caption: yes
  pdf_document: 
    toc: yes
    keep_tex: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(gganimate)
library(ggmosaic)
library(lubridate)
library(ggstream)
library(patchwork)
library(hrbrthemes)
library(ggbump)
library(scales)
library(ggforce)
library(jcolors)
library(here)
library(glue)
library(shadowtext)
library(RcppRoll)

theme_set(theme_ipsum_rc(
  base_size = 16,
  plot_title_size = 24,
  subtitle_size = 18,
  axis_text_size = 14,
  axis_title_size = 12,
  grid = "Y"
))
Sys.setlocale(category = "LC_ALL", locale = "en_US.UTF-8")
```

```{r include=FALSE}
evax_data <- read.csv2(here("data", "evax_group_bucket.csv"), sep = ",") %>%
  mutate(date = ymd(date)) %>%
  filter(!age_group == "-18", date < max(date))

last_date <- max(evax_data$date)
events_df <- tribble(
  ~date,             ~label,
  # ymd("2021-01-18"), "Mesures restrictives",
  # ymd("2021-01-25"), "Mesures restrictives",
  # ymd("2021-03-08"), "Allègement des mesures",
  ymd("2021-03-13"), "Beginning of the vaccination campaign",
  # ymd("2021-04-09"), "Restrictions pendant le Ramadan",
  # ymd("2021-05-09"), "Lockdown during the Aïd",
  # ymd("2021-05-17"), "Reopining of Restaurants and cafés",
  # ymd("2021-06-20"), "Fermeture de 4 gouvernorats",
  # ymd("2021-07-01"), "Renforcement des mesures dans plusieurs gouvernorats",
  ymd("2021-07-19"), "Vaccination for people older than 18",
)

aspect_ratio <- 3 / 4
export_W <- 12
export_H <- export_W * aspect_ratio
```

```{r}
line_plot <- evax_data %>%
  ggplot(aes(
    x = date,
    y = registered,
    color = age_group,
    fill = age_group
  )) +
  scale_y_continuous(labels = number_format()) +
  geom_line(lwd = 1) +
  labs(
    title = "Number of registrations on EVAX over time",
    x = "Date", y = "Number of registrations", color = "Age bucket",
    caption = "Iyed Ghedamsi\nhttps://iyedg.me"
  ) +
  scale_color_jcolors("pal5") +
  facet_wrap(~age_group)

ggsave(here("images/line_plot.png"),
  width = export_W,
  height = export_H
)

line_plot
```

```{r}
cum_line_plot <- evax_data %>%
  group_by(age_group) %>%
  mutate(cum_registered = cumsum(registered)) %>%
  ungroup() %>%
  ggplot(aes(
    x = date,
    y = cum_registered,
    color = age_group,
    fill = age_group
  )) +
  scale_y_continuous(labels = number_format()) +
  geom_line(lwd = 1) +
  labs(
    title = "Cumulative number of registrations on EVAX",
    x = "Date", y = "Number of registrations", color = "Age bucket",
    caption = "Iyed Ghedamsi\nhttps://iyedg.me"
  ) +
  scale_color_jcolors("pal5") +
  facet_wrap(~age_group)

ggsave(here("images/cum_line_plot.png"),
  width = export_W,
  height = export_H
)

cum_line_plot
```


```{r}
stream_plot <- evax_data %>%
  ggplot(aes(
    x = date,
    y = registered,
    fill = age_group,
    label = age_group
  )) +
  geom_stream(type = "ridge", bw = 0.5) +
  scale_y_continuous(label = number_format()) +
  scale_fill_jcolors("pal5") +
  ggtitle("Number of registrations on EVAX") +
  labs(x = "Date", y = "Number of registrations", fill = "Age Group",
    caption = "Iyed Ghedamsi\nhttps://iyedg.me"
       ) +
  geom_vline(aes(xintercept = ymd("2021-03-13")), lwd = 1.2, alpha = 0.6) +
  geom_text(aes(x = ymd("2021-03-13"), y = 30000, label = "Beginning of the vaccination campaign", angle = 90, vjust = -0.5),
    color = "black", alpha = 0.7, size = 5, inherit.aes = FALSE)
  # ) +
  # geom_vline(aes(xintercept = ymd("2021-07-19")), lwd = 1.2, alpha = 0.6) +
  # geom_shadowtext(
  #   aes(x = ymd("2021-07-19"), y = 20000, label = "Vaccination for people older than 18", angle = 90, vjust = -0.5),
  #   color = "white", alpha = 0.7, size = 5, inherit.aes = FALSE
  # )

stream_plot

ggsave(here("images/stream_plot.png"),
  width = export_W,
  height = export_H
)
```


```{r}
ranked_evax_data <- evax_data %>%
  filter(date >= ymd("2021-07-10")) %>%
  group_by(date) %>%
  mutate(age_group_rank = rank(-registered)) %>%
  ungroup()

bump_plot <- ranked_evax_data %>%
  ggplot(aes(x = date, y = age_group_rank, color = age_group)) +
  geom_bump(size = 1.5) +
  scale_color_jcolors("pal5") +
  scale_y_reverse(label = ordinal_format()) +
  labs(
    x = "Date",
    y = "Rank",
    color = "Age Group",
    title = "Ranking of age groups based on registrations per day",
    caption = "Iyed Ghedamsi\nhttps://iyedg.me"
  )

ggsave(here("images/bump_plot.png"),
  width = export_W,
  height = export_H
)
bump_plot
```

```{r}
evax_data %>%
  mutate(date_month = ymd(format(date, "%Y-%m-01"))) %>%
  group_by(date_month) %>%
  summarise(registered = sum(registered), invited = sum(invited)) %>%
  ungroup() %>%
  ggplot(aes(x = date_month, y = registered, label = number(registered))) +
  geom_col() +
  geom_text(color = "white", vjust = 1.5) + 
  scale_y_comma() +
  labs(title = "Number of registrations on EVAX by month",
       x = "Month", y = "Registrations",
    caption = "Iyed Ghedamsi\nhttps://iyedg.me"
       )

ggsave(here("images/reg_p_month_plot.png"),
  width = export_W,
  height = export_H
)
```


```{r}
data <- evax_data %>%
  group_by(age_group) %>%
  summarise(
    invited = sum(invited),
    registered = sum(registered)
  ) %>%
  ungroup() %>%
  pivot_longer(c("invited", "registered"),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(age_group = as.factor(age_group))

comparison_bar_plot <- data %>%
  ggplot(aes(
    x = age_group, y = ifelse(variable == "invited", value, -value),
    fill = variable,
    color = NULL,
    label = number(value, scale = 1 / 1000, suffix = "K"),
  )) +
  geom_bar(data = subset(data, variable == "registered"), stat = "identity") +
  geom_bar(data = subset(data, variable == "invited"), stat = "identity") +
  geom_text(
    data = subset(data, variable == "registered"),
    color = "black",
    position = position_stack(vjust = 0.5),
    size = 6
  ) +
  geom_text(
    data = filter(data, variable == "invited", value >= 200000),
    colour = "white",
    position = position_stack(vjust = 0.5),
    size = 6
  ) +
  geom_text(
    data = filter(data, variable == "invited", value <= 200000),
    colour = "black",
    vjust = -0.3,
    size = 6
  ) +
  scale_y_continuous(labels = NULL) +
  labs(
    x = "Age Group",
    y = "Number of people",
    title = "Number of registrations on EVAX vs. Number of convocations for vaccination",
    caption = "Iyed Ghedamsi\nhttps://iyedg.me"
  ) +
  scale_fill_jcolors("pal5",
    name = "",
    labels = c("invited" = "Convocations", "registered" = "Registrations")
  )
ggsave(here("images/comp_plot.png"),
  width = export_W,
  height = export_H
)
comparison_bar_plot
```

```{r}
evax_data %>%
  filter(age_group == "18-30") %>%
  arrange(desc(registered)) %>%
  head()
```

